"""
CS2 Auto-Cycling GOTV Spectator.

Automatically connects CS2 to GOTV relays for bettable matches,
cycles between matches to collect data for each one.

Flow:
1. Bot detects bettable CS2 matches needing data
2. Writes connect command to a cfg file
3. CS2 executes it via exec command
4. GSI receives live data for ~30 seconds
5. Cycles to next match

Usage:
- CS2 must be running with: -condebug +exec spectator_bot
- Or manually type 'exec spectator_bot' in CS2 console
"""
import asyncio
import os
import time
import logging
from typing import Optional

logger = logging.getLogger(__name__)

# CS2 paths
CS2_BASE = os.path.expanduser(
    "~/Library/Application Support/Steam/steamapps/common/Counter-Strike Global Offensive"
)
CS2_CFG = os.path.join(CS2_BASE, "game", "csgo", "cfg")
SPECTATOR_CFG = os.path.join(CS2_CFG, "spectator_bot.cfg")
GSI_CFG = os.path.join(CS2_CFG, "gamestate_integration_bot.cfg")


class CS2Spectator:
    """Manages CS2 GOTV spectating — auto-connects and cycles between matches."""

    CYCLE_INTERVAL = 30  # seconds per match before cycling
    CONNECT_DELAY = 8    # seconds to wait after connecting

    def __init__(self):
        self._gotv_queue: list[dict] = []  # [{id, ip, port, team_a, team_b}]
        self._current_index = 0
        self._running = False
        self._last_connect_time = 0
        self._task: Optional[asyncio.Task] = None

    def setup(self) -> bool:
        """Install GSI config and spectator cfg if CS2 is installed."""
        if not os.path.isdir(CS2_CFG):
            logger.warning(f"CS2 cfg folder not found at {CS2_CFG} — CS2 not installed?")
            return False

        # Copy GSI config
        gsi_src = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "cs2_config", "gamestate_integration_bot.cfg"
        )
        if os.path.exists(gsi_src) and not os.path.exists(GSI_CFG):
            import shutil
            shutil.copy2(gsi_src, GSI_CFG)
            logger.info(f"Installed GSI config to {GSI_CFG}")

        # Create initial spectator cfg
        self._write_cfg("// Spectator bot ready — waiting for GOTV address")
        logger.info("CS2 spectator ready")
        return True

    def add_gotv(self, match_id: str, gotv_ip: str, gotv_port: int = 27020,
                 team_a: str = "", team_b: str = ""):
        """Add a GOTV address to the spectating queue."""
        # Don't add duplicates
        for g in self._gotv_queue:
            if g["ip"] == gotv_ip and g["port"] == gotv_port:
                return

        self._gotv_queue.append({
            "id": match_id,
            "ip": gotv_ip,
            "port": gotv_port,
            "team_a": team_a,
            "team_b": team_b,
        })
        logger.info(f"[SPECTATOR] Added GOTV: {team_a} vs {team_b} @ {gotv_ip}:{gotv_port}")

    def remove_gotv(self, match_id: str):
        """Remove a finished match from the queue."""
        self._gotv_queue = [g for g in self._gotv_queue if g["id"] != match_id]

    async def start_cycling(self):
        """Start the auto-cycling loop."""
        self._running = True
        self._task = asyncio.create_task(self._cycle_loop())

    async def stop(self):
        self._running = False
        if self._task:
            self._task.cancel()
        self._write_cfg("disconnect")

    async def _cycle_loop(self):
        """Cycle between GOTV addresses."""
        while self._running:
            try:
                if not self._gotv_queue:
                    await asyncio.sleep(5)
                    continue

                # Pick next match
                self._current_index = self._current_index % len(self._gotv_queue)
                gotv = self._gotv_queue[self._current_index]

                # Connect to GOTV
                cmd = f"connect {gotv['ip']}:{gotv['port']}"
                self._write_cfg(cmd)
                logger.info(
                    f"[SPECTATOR] Connecting to {gotv['team_a']} vs {gotv['team_b']} "
                    f"@ {gotv['ip']}:{gotv['port']}"
                )

                # Wait for connection + data collection
                await asyncio.sleep(self.CYCLE_INTERVAL)

                # Move to next match
                self._current_index += 1

            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error(f"[SPECTATOR] Cycle error: {e}")
                await asyncio.sleep(5)

    def _write_cfg(self, command: str):
        """Write a command to the spectator cfg file."""
        try:
            with open(SPECTATOR_CFG, "w") as f:
                f.write(f"// Auto-generated by esports bot\n")
                f.write(f"// {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write(f"{command}\n")
        except Exception as e:
            logger.error(f"[SPECTATOR] Failed to write cfg: {e}")

    def launch_cs2_gotv(self, gotv_ip: str, gotv_port: int = 27020):
        """Launch CS2 and connect to a GOTV relay via Steam protocol."""
        import subprocess
        url = f"steam://connect/{gotv_ip}:{gotv_port}"
        try:
            subprocess.Popen(["open", url])
            logger.info(f"[SPECTATOR] Launched CS2 → {gotv_ip}:{gotv_port}")
        except Exception as e:
            logger.error(f"[SPECTATOR] Failed to launch CS2: {e}")

    def get_status(self) -> dict:
        """Get current spectator status for dashboard."""
        return {
            "queue_size": len(self._gotv_queue),
            "current_index": self._current_index % max(1, len(self._gotv_queue)),
            "current_match": self._gotv_queue[self._current_index % len(self._gotv_queue)] if self._gotv_queue else None,
            "running": self._running,
        }
